import type { Metadata } from "next";
import { Preahvihear } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const preahvihear = Preahvihear({
  subsets: ["latin"], // hỗ trợ tiếng Việt
  weight: "400", // font này thường chỉ có 400
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${preahvihear.className} w-full`}
      >
        
        {children}
      </body>
    </html>
  );
}
